---
title: "Tableau de bord ITCI "
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE, message=FALSE}
library(flexdashboard)
source("01-maps.R")
source("02-line-charts.R")
```


# CEDEAO

Column {data-width=500}
-------------------------------------

### ITCI, 2021

When you create an account, we remember exactly what you've read, so you always come right back where you left off. You also get notifications, here and via email, whenever someone replies to you. And you can like posts to share the love

```{r, message=FALSE, warning=FALSE,cache=FALSE}
tm_cedeao()
```
Column {data-width=500}
-------------------------------------

### ITCI, 16

```{r}
ln_cedeao()
```

### ITCI, 2021

```{r}
ln_cedeao()
```

# CEMAC


# IGAD
Column {data-width=500}
-------------------------------------

### ITCI, 2021

When you create an account, we remember exactly what you've read, so you always come right back where you left off. You also get notifications, here and via email, whenever someone replies to you. And you can like posts to share the love

```{r, message=FALSE, warning=FALSE,cache=FALSE}
tm_igad()
```
Column {data-width=350}
-------------------------------------

### ITCI, 16

```{r}
tm_igad(year = 2016)
```

### ITCI, 2021

```{r}
tm_igad(year = 2012)
```


# MAGRHEB


